***

## 🇧🇷 Seja bem vindo!
Me chamo Ígor Silva, sou estudante de ciência de dados.

Este é um notebook que traz alguns métodos do pandas para análise inicial de dados. O objetivo é familiarizar e ajudar novos estudantes na fase inicial da análise.

Para saber mais, acesse:
* [LinkedIn](https://www.linkedin.com/in/igordrsilva/)
* [Github](https://github.com/igordrsilva)

Divirta-se!

## 🇺🇸 Welcome!
My name is Ígor Silva, I'm a Data Science student.

This notebook brings some pandas methos to initial data analysis. The goal is familiarize and help new students on data analysis.

To see more, visit:
* [LinkedIn](https://www.linkedin.com/in/igordrsilva/)
* [Github](https://github.com/igordrsilva)

Enjoy!

***

## 10 Principals Methods in Python to Initial Data Analysis

The dataset we'll use in this example is available on Kaggle: [Gym Membership Dataset](https://www.kaggle.com/datasets/ka66ledata/gym-membership-dataset)

### ⤵️ Imports

In [ ]:
import kagglehub
import pandas as pd
import os

path = kagglehub.dataset_download("ka66ledata/gym-membership-dataset")

Using Colab cache for faster access to the 'gym-membership-dataset' dataset.

### 💡 Starting with Data Analysis

#### 1. `pd.DataFrame().head()`
It shows the five first data's lines. Here we can have an idea of what kind of data we'll work.

In [ ]:
data = pd.read_csv(os.path.join(path, "gym_membership.csv"))
data.head()

,id,gender,birthday,Age,abonoment_type,visit_per_week,days_per_week,attend_group_lesson,fav_group_lesson,avg_time_check_in,avg_time_check_out,avg_time_in_gym,drink_abo,fav_drink,personal_training,name_personal_trainer,uses_sauna
0,1,Female,1997-04-18,27,Premium,4,"Mon, Sat, Tue, Wed",True,"Kickboxen, BodyPump, Zumba",19:31:00,21:27:00,116,False,NaN,False,NaN,True
1,2,Female,1977-09-18,47,Standard,3,"Mon, Sat, Wed",False,NaN,19:31:00,20:19:00,48,False,NaN,True,Chantal,False
2,3,Male,1983-03-30,41,Premium,1,Sat,True,XCore,08:29:00,10:32:00,123,True,"berry_boost, lemon",True,Mike,False
3,4,Male,1980-04-12,44,Premium,3,"Sat, Tue, Wed",False,NaN,09:54:00,11:33:00,99,True,passion_fruit,True,Mike,True
4,5,Male,1980-09-10,44,Standard,2,"Thu, Wed",True,"Running, Yoga, Zumba",08:29:00,09:19:00,50,False,NaN,True,Mike,False

**🗣️ An extra tip:** `pd.DataFrame().tail()`

Returns the five last data's lines.

In [ ]:
data.tail()

,id,gender,birthday,Age,abonoment_type,visit_per_week,days_per_week,attend_group_lesson,fav_group_lesson,avg_time_check_in,avg_time_check_out,avg_time_in_gym,drink_abo,fav_drink,personal_training,name_personal_trainer,uses_sauna
995,996,Female,1984-09-22,40,Standard,3,"Thu, Tue, Wed",False,NaN,20:56:00,22:42:00,106,False,NaN,False,NaN,False
996,997,Female,2008-11-19,15,Standard,3,"Fri, Mon, Sun",True,"XCore, Zumba",09:14:00,11:28:00,134,True,"orange, lemon",False,NaN,True
997,998,Male,1984-10-05,40,Standard,2,"Fri, Tue",False,NaN,17:21:00,19:53:00,152,True,"coconut_pineapple, black_currant",True,Jeffrey,True
998,999,Male,2001-02-22,23,Standard,4,"Mon, Sun, Thu, Tue",True,"HIT, XCore",10:23:00,12:29:00,126,True,berry_boost,True,Jeffrey,False
999,1000,Female,2006-05-07,18,Premium,2,"Thu, Tue",False,NaN,16:41:00,19:00:00,139,True,"passion_fruit, coconut_pineapple",False,NaN,False

#### 2. `pd.DataFrame().shape`
Returns the dataset dimention (lines, columns)

In [ ]:
data.shape

(1000, 17)

#### 3. `pd.DataFrame().info()`
Shows the structural resume: columns name, count of null values and types of data.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1000 non-null   int64
 1   gender                 1000 non-null   object
 2   birthday               1000 non-null   object
 3   Age                    1000 non-null   int64
 4   abonoment_type         1000 non-null   object
 5   visit_per_week         1000 non-null   int64
 6   days_per_week          1000 non-null   object
 7   attend_group_lesson    1000 non-null   bool
 8   fav_group_lesson       503 non-null    object
 9   avg_time_check_in      1000 non-null   object
 10  avg_time_check_out     1000 non-null   object
 11  avg_time_in_gym        1000 non-null   int64
 12  drink_abo              1000 non-null   bool
 13  fav_drink              496 non-null    object
 14  personal_training      1000 non-null   bool
 15  name_personal_trainer  518 non-null    object
 16  uses_sauna             1000 non-null   bool
dtypes: bool(4), int64(4), object(9)
memory usage: 105.6+ KB

#### 4. `pd.DataFrame().describe()`
Shows main descriptives statistics (returns numerics data by default).

In [ ]:
data.describe()

                id          Age  visit_per_week  avg_time_in_gym
count  1000.000000  1000.000000     1000.000000      1000.000000
mean    500.500000    30.604000        2.682000       105.260000
std     288.819436    10.817958        1.241941        43.557177
min       1.000000    12.000000        1.000000        30.000000
25%     250.750000    21.000000        2.000000        67.000000
50%     500.500000    30.000000        3.000000       104.000000
75%     750.250000    40.000000        3.000000       143.000000
max    1000.000000    49.000000        5.000000       180.000000

**🗣️ An extra tip:** `pd.DataFrame().describe(include='object')`

Returns some statistics of categorical data.

In [ ]:
data.describe(include='object')

,gender,birthday,abonoment_type,days_per_week,fav_group_lesson,avg_time_check_in,avg_time_check_out,fav_drink,name_personal_trainer
count,1000,1000,1000,1000,503,1000,1000,496,518
unique,2,974,2,115,253,556,572,36,4
top,Female,1976-09-28,Standard,Sun,BodyPump,17:57:00,14:08:00,coconut_pineapple,Chantal
freq,503,2,507,37,20,6,6,53,153

#### 5. `pd.DataFrame()[column].nunique()`
Returns the count of unique values in a column.

In [ ]:
data['fav_group_lesson'].nunique()

253

#### 6. `pd.DataFrame()[column].value_counts()`
Returns the frequency of each value in a column.

In [ ]:
data['fav_group_lesson'].value_counts()

fav_group_lesson
BodyPump                           20
Yoga                               20
LesMiles                           19
Pilates                            18
XCore                              18
                                   ..
XCore, Kickboxen, Zumba             1
LesMiles, Zumba                     1
Pilates, Kickboxen, BodyBalance     1
LesMiles, Zumba, Spinning           1
HIT, XCore                          1
Name: count, Length: 253, dtype: int64

#### 7. `pd.DataFrame()[column].mean()`
Returns the mean of column value.

In [ ]:
data['visit_per_week'].mean()

np.float64(2.682)

**🗣️ An extra tip:** `pd.DataFrame[column].mode()` e `pd.DataFrame[column].median()`

More of central tendency statistics. Returns the mode and median of column value.

In [ ]:
data['visit_per_week'].mode()

0    3
Name: visit_per_week, dtype: int64

In [ ]:
data['visit_per_week'].median()

3.0

#### 8. `pd.DataFrame()[column].std()`
Calculate the standard deviation.

In [ ]:
data['visit_per_week'].std()

1.2419413908950876

#### 9. `pd.DataFrame().dtypes`
Returns the columns types of dataset.

In [ ]:
data.dtypes

id                        int64
gender                   object
birthday                 object
Age                       int64
abonoment_type           object
visit_per_week            int64
days_per_week            object
attend_group_lesson        bool
fav_group_lesson         object
avg_time_check_in        object
avg_time_check_out       object
avg_time_in_gym           int64
drink_abo                  bool
fav_drink                object
personal_training          bool
name_personal_trainer    object
uses_sauna                 bool
dtype: object

#### 10. `pd.DataFrame().columns`
Returns all columns names of dataset.

In [ ]:
data.columns

Index(['id', 'gender', 'birthday', 'Age', 'abonoment_type', 'visit_per_week',
       'days_per_week', 'attend_group_lesson', 'fav_group_lesson',
       'avg_time_check_in', 'avg_time_check_out', 'avg_time_in_gym',
       'drink_abo', 'fav_drink', 'personal_training', 'name_personal_trainer',
       'uses_sauna'],
      dtype='object')

***

## 🇧🇷 Espero que tenham gostado!
Caso queira mais conteúdos como este, você pode me encontrar no [LinkedIn](https://www.linkedin.com/in/igordrsilva/) ou também encontrar meus estudos no [Github](https://github.com/igordrsilva).

Abraços, até a próxima!

## 🇺🇸 I hope you had fun!
If you want more contents like this, you can find me on [LinkedIn](https://www.linkedin.com/in/igordrsilva/) or also find my studies on [Github](https://github.com/igordrsilva).

See you there!

***